//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NotesMarketPlace.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_NoteReviews
    {
        public int Id { get; set; }
        public int Note_id { get; set; }
        public int ReviewedBy_id { get; set; }
        public int IsDownloaded_id { get; set; }
        public decimal Ratings { get; set; }
        public string Reviews { get; set; }
        public Nullable<System.DateTime> DateAdded { get; set; }
        public Nullable<int> AddedBy { get; set; }
        public Nullable<System.DateTime> DateEdited { get; set; }
        public Nullable<int> EditedBy { get; set; }
        public bool IsActive { get; set; }
    
        public virtual tbl_Notes tbl_Notes { get; set; }
        public virtual tbl_Users tbl_Users { get; set; }
        public virtual tbl_Users tbl_Users1 { get; set; }
    }
}
