//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NotesMarketPlace.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Notes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Notes()
        {
            this.tbl_Download = new HashSet<tbl_Download>();
            this.tbl_NoteAttachments = new HashSet<tbl_NoteAttachments>();
            this.tbl_NoteReviews = new HashSet<tbl_NoteReviews>();
            this.tbl_ReportedNotes = new HashSet<tbl_ReportedNotes>();
        }
    
        public int Id { get; set; }
        public int Seller_id { get; set; }
        public int Status { get; set; }
        public Nullable<int> StatusActionedBy { get; set; }
        public string AdminRemarks { get; set; }
        public Nullable<System.DateTime> PublishedDate { get; set; }
        public string NoteTitle { get; set; }
        public int NoteCategory_id { get; set; }
        public string DisplayPicture { get; set; }
        public Nullable<int> NoteType_id { get; set; }
        public Nullable<int> NumberOfPages { get; set; }
        public string Description { get; set; }
        public string University { get; set; }
        public Nullable<int> Country_id { get; set; }
        public string Course { get; set; }
        public string CourseCode { get; set; }
        public string Professor { get; set; }
        public Nullable<bool> IsPaid { get; set; }
        public Nullable<decimal> SellingPrice { get; set; }
        public string NotesPreview { get; set; }
        public Nullable<System.DateTime> DateAdded { get; set; }
        public Nullable<int> AddedBy { get; set; }
        public Nullable<System.DateTime> DateEdited { get; set; }
        public Nullable<int> EditedBy { get; set; }
        public bool IsActive { get; set; }
    
        public virtual tbl_Country tbl_Country { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Download> tbl_Download { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_NoteAttachments> tbl_NoteAttachments { get; set; }
        public virtual tbl_NoteCategory tbl_NoteCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_NoteReviews> tbl_NoteReviews { get; set; }
        public virtual tbl_NoteType tbl_NoteType { get; set; }
        public virtual tbl_ReferenceData tbl_ReferenceData { get; set; }
        public virtual tbl_Users tbl_Users { get; set; }
        public virtual tbl_Users tbl_Users1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_ReportedNotes> tbl_ReportedNotes { get; set; }
    }
}
