//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NoteMarketPlace.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NoteMarketPlaceEntities : DbContext
    {
        public NoteMarketPlaceEntities()
            : base("name=NoteMarketPlaceEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_ContactUs> tbl_ContactUs { get; set; }
        public virtual DbSet<tbl_Country> tbl_Country { get; set; }
        public virtual DbSet<tbl_Download> tbl_Download { get; set; }
        public virtual DbSet<tbl_NoteAttachments> tbl_NoteAttachments { get; set; }
        public virtual DbSet<tbl_NoteCategory> tbl_NoteCategory { get; set; }
        public virtual DbSet<tbl_NoteReviews> tbl_NoteReviews { get; set; }
        public virtual DbSet<tbl_Notes> tbl_Notes { get; set; }
        public virtual DbSet<tbl_NoteType> tbl_NoteType { get; set; }
        public virtual DbSet<tbl_ReferenceData> tbl_ReferenceData { get; set; }
        public virtual DbSet<tbl_ReportedNotes> tbl_ReportedNotes { get; set; }
        public virtual DbSet<tbl_SystemConfiguration> tbl_SystemConfiguration { get; set; }
        public virtual DbSet<tbl_UserProfile> tbl_UserProfile { get; set; }
        public virtual DbSet<tbl_UserRoles> tbl_UserRoles { get; set; }
        public virtual DbSet<tbl_Users> tbl_Users { get; set; }
    }
}
